### PR TITLE
Closes #53 Now switch has a default element

### LINKED ISSUE #53: "switch" block should insert new element to the previous position
How to reproduce the problem:

```scala
val rx: Var[Boolean] = true

div(
  cls := "outer",
  switch(
    rx map {
      if (_) span(cls := "inner-1-true")
      else span(cls := "inner-1-false")
    }
  ),
  span(cls := "inner-2")
)

/* 
<div class="outer">
  <span class="inner-1-true"></span>
  <span class="inner-2"></span>
</div>
 */


// Later
rx.pull(false)

/* 
<div class="outer">
  <span class="inner-2"></span>
  <span class="inner-1-false"></span>
</div>
 */
```

Adding an outer element (for **switch** block) leads to adding unnecessary CSS-classes and styles.

We should add an empty element (in a position of the switch), and then replace it when the state changes.

### PR DESCRIPTION
**Pull request by vsuharnikov**
Subject

### CODE REVIEW

File: moorka-ui/src/main/scala/moorka/ui/components/html/ElementSwitcher.scala [hunk 1]
```diff
@@ -10,21 +10,23 @@ import vaska.JSObj
 class ElementSwitcher(state: Rx[ElementBase]) extends ElementExtension {
 
   val reaper = Reaper()
-  var previous: ElementBase = null
+  private var current: ElementBase = null
```
Comment (fomkin) [inline moorka-ui/src/main/scala/moorka/ui/components/html/ElementSwitcher.scala]: private[this]
